# Generated by Django 3.2.6 on 2021-08-24 10:11

import chat_system.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_system', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='default.png', upload_to=chat_system.models.upload_directory),
        ),
    ]
