# Generated by Django 3.2.6 on 2021-08-28 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_system', '0004_auto_20210824_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='favourite',
            field=models.BooleanField(default=False),
        ),
    ]
