# Generated by Django 3.2.6 on 2021-08-28 21:02

import chat_system.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_system', '0005_contact_favourite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', models.ImageField(upload_to=chat_system.models.story_upload_directory)),
                ('datetime', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_user_requests_created', to='chat_system.user')),
            ],
        ),
    ]
