# Generated by Django 3.2.6 on 2021-08-29 23:37

import chat_system.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('chat_system', '0009_auto_20210829_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=django_resized.forms.ResizedImageField(crop=None, default='default.png', force_format=None, keep_meta=True, quality=0, size=[300, 300], upload_to=chat_system.models.upload_directory),
        ),
    ]
