# Generated by Django 3.2.6 on 2021-08-29 23:38

import chat_system.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('chat_system', '0010_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='story',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=0, size=[700, 700], upload_to=chat_system.models.story_upload_directory),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=django_resized.forms.ResizedImageField(crop=None, default='default.png', force_format=None, keep_meta=True, quality=0, size=[500, 500], upload_to=chat_system.models.upload_directory),
        ),
    ]
